# Generated by Django 5.1.6 on 2025-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_crypto", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncryptedFile",
        ),
    ]
