# Generated by Django 5.1.6 on 2025-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_crypto", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="deleted_files/")),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="EncryptedFile",
        ),
    ]
